# Generated by Django 4.2.7 on 2023-11-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('landing_url', models.URLField()),
                ('weight', models.IntegerField()),
                ('target_country', models.CharField(max_length=100)),
                ('target_gender', models.CharField(max_length=1)),
                ('reward', models.FloatField()),
            ],
        ),
    ]
